---
title: "Social Science - CDC 2024"
author: "Sean Shen"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE, warning=F}
library(tidyverse)
library(nortest)
library(cluster)
library(factoextra)
travel_df <- read_csv("Social_Science_Dataset.csv")
```


```{r, include=F}
#data cleaning
head(travel_df)
names(travel_df)

category <- c("Unique user id",
"churches",
"resorts",
"beaches", 
"parks", 
"theatres", 
"museums", 
"malls", 
"zoo", 
"restaurants", 
"pubs/bars", 
"local services",
"burger/pizza shops", 
"hotels/other lodgings", 
"juice bars", 
"art galleries", 
"dance clubs", 
"swimming pools", 
"gyms", 
"bakeries",
"beauty & spas", 
"cafes",
"view points",
"monuments",
"gardens")

travel_df=travel_df[-1, -26]

#rename columns
for (i in 1:ncol(travel_df)){
  names(travel_df)[i]=category[i]
}

#remove "User " from `Unique user id`
for (i in 1:nrow(travel_df)){
  travel_df$`Unique user id` = 
    str_replace(travel_df$`Unique user id`, "User ", "")
}


#convert numbers from character to double
for (i in 2:ncol(travel_df)){
  travel_df[[i]]=as.numeric(travel_df[[i]])
}

names(travel_df)
head(travel_df)

```

```{r}
#cleaned data
head(travel_df)
```


```{r}
#check normality using Anderson-Darling Test
normality_by_category <- data.frame(category=c(rep(-1, 24)),
                                   A=c(rep(-1, 24)), 
                                      `p-value`=c(rep(-1, 24)))
A=c(rep(-1, 24))
p=c(rep(-1, 24))

normality_by_category$category=names(travel_df)[-1]

for (i in 2:25){
  temp <- travel_df[[i]][travel_df[[i]]!=0]
  
  A[i-1]=ad.test(temp)[1]
  p[i-1]=ad.test(temp)[2]
}
normality_by_category$A=unlist(A)
normality_by_category$`p-value`=unlist(p)

normality_by_category$normality=ifelse(normality_by_category$`p-value`>=0.05, 
                                       1, 0)

normality_by_category<- normality_by_category[, -3]
normality_by_category
```

```{r}
#histograms to see distributions of all the categories
for (i in 2:25){
  temp <- travel_df[[i]][travel_df[[i]]!=0]
  hist(temp, main=names(travel_df)[i])
}
```



```{r}
set.seed(123)
travel_kms <- na.omit(travel_df[, -1])


sil <- c(rep(-2, 9))

#k=2 to k=10
for (k in 2:10){
  kmeans_out <- kmeans(travel_kms, centers = k, nstart=25)
  sil_score<- silhouette(kmeans_out$cluster, dist(travel_kms))
  sil[k-1]<- summary(sil_score)$avg.width
}
which.max(sil)+1 #k=9 gives the highest silhouette value



wcss <- c(rep(-1,14))
for (k in 2:15){
  wcss[k-1]<- kmeans(travel_df_train[, -1], centers = k,
                     nstart=25)$tot.withinss
}

wcss

kmeans.out <- kmeans(travel_kms, centers = 9, nstart=30)
kmeans.out
```

